-- =====================================================
-- DESACTIVAR RLS PARA DESARROLLO
-- =====================================================
-- ⚠️ SOLO PARA DESARROLLO - NO USAR EN PRODUCCIÓN

ALTER TABLE senderos DISABLE ROW LEVEL SECURITY;
ALTER TABLE planes DISABLE ROW LEVEL SECURITY;
ALTER TABLE precios_senderos DISABLE ROW LEVEL SECURITY;
ALTER TABLE tarifas_basicas DISABLE ROW LEVEL SECURITY;
ALTER TABLE tarifas_guias DISABLE ROW LEVEL SECURITY;
ALTER TABLE fechas_programadas_top DISABLE ROW LEVEL SECURITY;
ALTER TABLE opciones_dinamicas DISABLE ROW LEVEL SECURITY;
ALTER TABLE reservas DISABLE ROW LEVEL SECURITY;
ALTER TABLE reservas_plan_basico DISABLE ROW LEVEL SECURITY;
ALTER TABLE reservas_plan_top DISABLE ROW LEVEL SECURITY;
ALTER TABLE reservas_plan_dinamico DISABLE ROW LEVEL SECURITY;
ALTER TABLE reservas_opciones_dinamicas DISABLE ROW LEVEL SECURITY;
